### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to ProjectKorra v1.8.8 for MC 1.13.2+

### ISSUE THREAD

**Issue by andris155** [ProjectKorra/ProjectKorra#1000]
```
[19:47:32] [Async Chat Thread - #32/ERROR]: Could not pass event AsyncPlayerChatEvent to ProjectKorra v1.8.8 for MC 1.13.2+
java.lang.NullPointerException: null
	at com.projectkorra.projectkorra.PKListener.onPlayerChat(PKListener.java:664) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor859.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-638]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1696) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1611) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.13.2.jar:git-Paper-638]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?
```
Paper 1.13.2
ProjectKorra v1.8.8

**Comment by PhanaticD** [comment]
this was fixed already, you can compile the 1.13 branch to get latest changes
