### ISSUE TITLE
IceSpike not working with bottlebending

### ISSUE THREAD

**Issue by Varhagna** [ProjectKorra/ProjectKorra#1080]
![image](https://user-images.githubusercontent.com/19560788/89721649-f9f21300-d994-11ea-818d-686598ae3409.png)

**Comment by Varhagna** [comment]
```[16:45:01 WARN]: java.lang.NullPointerException
[16:45:01 WARN]: 	at com.projectkorra.projectkorra.ability.WaterAbility.isWaterbendable(WaterAbility.java:279)
[16:45:01 WARN]: 	at com.projectkorra.projectkorra.ability.WaterAbility.isWaterbendable(WaterAbility.java:123)
[16:45:01 WARN]: 	at com.projectkorra.projectkorra.ability.WaterAbility.isWaterbendable(WaterAbility.java:119)
[16:45:01 WARN]: 	at com.projectkorra.projectkorra.waterbending.ice.IceSpikeBlast.progress(IceSpikeBlast.java:160)
[16:45:01 WARN]: 	at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:274)
[16:45:01 WARN]: 	at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:117)
[16:45:01 WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81)
[16:45:01 WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[16:45:01 WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1059)
[16:45:01 WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354)
[16:45:01 WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1007)
[16:45:01 WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:846)
[16:45:01 WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[16:45:01 WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:45:01 ERROR]: com.projectkorra.projectkorra.waterbending.ice.IceSpikeBlast@6fdb018[
```
FOUND IT :)
