### ISSUE TITLE
Project Korra & KingdomsX Plugin Incompatibility

### ISSUE THREAD

**Issue by JustAHuman-xD** [ProjectKorra/ProjectKorra#1206]
1. Instance of the Error:
 [13:46:21] [Server thread/WARN]: [ProjectKorra] Task #114 for ProjectKorra v1.9.3 generated an exception
java.lang.NoSuchMethodError: 'org.kingdoms.constants.kingdom.Kingdom org.kingdoms.constants.land.Land.getKingdom()'
    at com.projectkorra.projectkorra.GeneralMethods.isRegionProtectedFromBuildPostCache(GeneralMethods.java:1680) ~[ProjectKorra-1.9.3.jar:?]
    at com.projectkorra.projectkorra.GeneralMethods.isRegionProtectedFromBuild(GeneralMethods.java:1529) ~[ProjectKorra-1.9.3.jar:?]
    at com.projectkorra.projectkorra.GeneralMethods.isRegionProtectedFromBuild(GeneralMethods.java:1535) ~[ProjectKorra-1.9.3.jar:?]
    at com.projectkorra.projectkorra.airbending.AirBlast.progress(AirBlast.java:317) ~[ProjectKorra-1.9.3.jar:?]
    at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:275) ~[ProjectKorra-1.9.3.jar:?]
    at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:117) ~[ProjectKorra-1.9.3.jar:?]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-399]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-399]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-399]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-399]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-399]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-399]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-399]
    at java.lang.Thread.run(Unknown Source) ~[?:?]
    The console gets spammed with errors such as this at a constant rate due to bending.
Server Version: 1.17.1
Kingdoms Version: 1.13.3.1
Log: 
[2022-05-07-2_1.log.gz](https://github.com/ProjectKorra/ProjectKorra/files/8647731/2022-05-07-2_1.log.gz)

**Comment by StrangeOne101** [comment]
Fixed in #1221
