### ISSUE TITLE
WaterSpout bug? Unable to do the normal WaterSpout variation

### ISSUE THREAD

**Issue by nattouu** [ProjectKorra/ProjectKorra#1235]
I'm not sure how this would help, but I was unable to do the normal WaterSpout and only the Wave variation.
The plugins and abilities that I have in my server is ProjectAddon, AvatachTweaks, BendingGUI.

Update 1: I apologize for my brevity, upon removing AvatachTweaks from my plugins, the WaterSpout is working BUT with creative mode-like flight state and unnaturally fast speed.

 I also found that upon switching to creative mode and flying,  I am no longer moving in normal flight speed but instead unnaturally fast speed just like the Update 1.

[02:13:46 ERROR]: Could not pass event PlayerInteractEvent to ProjectKorra v1.10.1
java.lang.NullPointerException: Cannot invoke "com.projectkorra.projectkorra.waterbending.WaterSpoutWave$AbilityType.equals(Object)" because "wave.type" is null
        at com.projectkorra.projectkorra.waterbending.WaterSpoutWave.removeOldType(WaterSpoutWave.java:459) ~[ProjectKorra-1.10.1.jar:?]
        at com.projectkorra.projectkorra.waterbending.WaterSpoutWave.progress(WaterSpoutWave.java:165) ~[ProjectKorra-1.10.1.jar:?]
        at com.projectkorra.projectkorra.waterbending.WaterSpoutWave.<init>(WaterSpoutWave.java:136) ~[ProjectKorra-1.10.1.jar:?]
        at com.projectkorra.projectkorra.waterbending.WaterSpout.<init>(WaterSpout.java:66) ~[ProjectKorra-1.10.1.jar:?]
        at com.projectkorra.projectkorra.PKListener.onPlayerSwing(PKListener.java:1724) ~[ProjectKorra-1.10.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor130.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1778]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2849) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:13:46 WARN]: java.lang.NullPointerException: Cannot invoke "com.projectkorra.projectkorra.waterbending.WaterSpoutWave$AbilityType.equals(Object)" because "wave.type" is null
[02:13:46 WARN]:        at ProjectKorra-1.10.1.jar//com.projectkorra.projectkorra.waterbending.WaterSpoutWave.removeOldType(WaterSpoutWave.java:459)
[02:13:46 WARN]:        at ProjectKorra-1.10.1.jar//com.projectkorra.projectkorra.waterbending.WaterSpoutWave.progress(WaterSpoutWave.java:165)
[02:13:46 WARN]:        at ProjectKorra-1.10.1.jar//com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:277)
[02:13:46 WARN]:        at ProjectKorra-1.10.1.jar//com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:117)
[02:13:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[02:13:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[02:13:46 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1520)
[02:13:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[02:13:46 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1444)
[02:13:46 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1214)
[02:13:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[02:13:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:13:46 ERROR]: com.projectkorra.projectkorra.waterbending.WaterSpoutWave@2a67b36d[
  radius=3.8
  charging=false
  iceWave=false
  iceOnly=false
  moving=false
  plant=true
  collidable=false
  revertIceSphere=true
  progressCounter=2
  time=1663352026669
  cooldown=6000
  revertSphereTime=30000
  selectRange=6.0
  speed=1.3
  chargeTime=500.0
  flightDuration=2500.0
  waveRadius=1.5
  thawRadius=10.0
  damage=3.0
  animationSpeed=1.2
  type=CLICK
  animation=<null>
  sourceBlock=<null>
  direction=<null>
  origin=<null>
  location=<null>
  affectedEntities=[]
  tasks=[]
  affectedBlocks={}
  player=CraftPlayer{name=Nattou_}
  bPlayer=com.projectkorra.projectkorra.BendingPlayer@1b8a72eb[
  slowTime=0
  player=CraftPlayer{name=Nattou_}
  stance=<null>
  tremorSense=true
  illumination=true
  chiBlocked=false
  player=CraftPlayer{name=Nattou_}
  uuid=2f6de3e0-eb0d-342f-9bc2-06ccc349d82b
  permaRemoved=false
  toggled=true
  allPassivesToggled=true
  loading=false
  elements=[Water]
  subelements=[Ice, Healing, Plant]
  abilities={1=WaterSpout}
  cooldowns={}
  toggledElements=[]
  toggledPassives=[]
  cooldownManager=com.projectkorra.projectkorra.util.DBCooldownManager@22176bd9
  currentSlot=0
  lastAccessed=1663351993969
  uncacheTime=30000
  uncache=<null>
]
  flightHandler=com.projectkorra.projectkorra.util.FlightHandler@2998abc
  attributeModifiers={}
  attributeValues={}
  started=true
  removed=true
  hidden=false
  id=-2147483640
  startTime=1663352026669
  startTick=743
  attributesModified=true

**Comment by Dreig-PSD** [comment]
Hi! It's bug with AvatachTweaks. It's fixed already, try the latest version =)
It's caused by WaterSourceParticles, but I fixed it, yes.

**Comment by Dreig-PSD** [comment]
load AvatachTweaks 0.2.8
https://projectkorra.com/forum/resources/avatachtweaks.457/
![image](https://user-images.githubusercontent.com/60939608/190700388-7f34cfd0-3aa6-4fd6-a5fc-218d0c87bb2e.png)

**Comment by nattouu** [comment]
> load AvatachTweaks 0.2.8 https://projectkorra.com/forum/resources/avatachtweaks.457/ ![image](https://user-images.githubusercontent.com/60939608/190700388-7f34cfd0-3aa6-4fd6-a5fc-218d0c87bb2e.png)

I see, but I am already using the latest 0.2.8 version prior to the issue.
It was working fine for a while I started the server but after while the issue starts to appear again.

**Comment by Dreig-PSD** [comment]
> 

Can we try to fix this problem in discord? Dreig_Michihi#8876

**Comment by nattouu** [comment]
I'll be closing this issue as it was not caused by the PK-Plugin.
