### ISSUE TITLE
Hook with GriefPrevention doesn't work!!

### ISSUE THREAD

**Issue by LincolnJota** [ProjectKorra/ProjectKorra#1301]
Hello, my server runs with Paper 1.19.4

I can use bendings in protections and kill others players even with config -> RespectGriefPrevention = true.

After death, my console logger the stacktrace: 
```
[17:23:03 ERROR]: Could not pass event PlayerDeathEvent to ProjectKorra v1.11.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "killer" is null
        at com.projectkorra.projectkorra.PKListener.onPlayerDeath(PKListener.java:1121) ~[ProjectKorra-1.11.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor489.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-538]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:925) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:917) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1480) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:965) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1086) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftLivingEntity.damage(CraftLivingEntity.java:382) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftLivingEntity.damage(CraftLivingEntity.java:367) ~[paper-1.19.4.jar:git-Paper-538]
        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:214) ~[ProjectKorra-1.11.2.jar:?]
        at com.projectkorra.projectkorra.firebending.util.FireDamageTimer.dealFlameDamage(FireDamageTimer.java:76) ~[ProjectKorra-1.11.2.jar:?]
        at com.projectkorra.projectkorra.PKListener.onEntityDamageEvent(PKListener.java:574) ~[ProjectKorra-1.11.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor507.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-538]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:252) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1180) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1154) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:983) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1214) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2148) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1058) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1383) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:965) ~[?:?]
```

**Comment by Killer-Bunny** [comment]
same problem
