### ISSUE TITLE
NPE PlayerAnimationEvent

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#151]
(Jun-24|07:09:44) [SEVERE] Could not pass event PlayerAnimationEvent to ProjectKorra v1.7.0 BETA 10
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1178)
    at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:18)
    at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1)
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.projectkorra.ProjectKorra.PKListener.onPlayerSwing(PKListener.java:1221)
    at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
    ... 15 more

**Comment by jacklin213** [comment]
What version of PK where u running when you reported this, #152 and #157

**Comment by PhanaticD** [comment]
i compiled it off github, so I believe whatever state it was at on the date I reported this

**Comment by PhanaticD** [comment]
using the latest version as of today I noticed this error: http://pastebin.com/hdphccXW

**Comment by jacklin213** [comment]
@PhanaticD thank you so much for reporting this error, luckily I am able to fix it before we release the beta

**Comment by OmniCypher-** [comment]
These issues should be resolved in the latest build
