### ISSUE TITLE
NPE PlayerToggleSneakEvent

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#152]
(Jun-24|07:13:03) [SEVERE] Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.7.0 BETA 10
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1193)
    at net.minecraft.server.v1_8_R3.PacketPlayInEntityAction.a(SourceFile:43)
    at net.minecraft.server.v1_8_R3.PacketPlayInEntityAction.a(SourceFile:9)
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.projectkorra.ProjectKorra.PKListener.onPlayerSneak(PKListener.java:1037)
    at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
    ... 15 more

**Comment by curz46** [comment]
@OmniCypher- old and abandoned, needs to be closed.
