### ISSUE TITLE
NCP Exemption NullPointerException on damageEntity() in DamageHandler.java

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#577]
Running latest ProjectKorra (commit https://github.com/ProjectKorra/ProjectKorra/commit/7ed5bcd01bf49b8e74e4464d98e6171c1e97d2dd) and NCP build 1022.

```
[01:39:56] [Server thread/ERROR]: Could not pass event EntityDamageEvent to ProjectKorra v1.8.0
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-866]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-866]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-866]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-866]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-866]
    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.10.2.jar:git-Paper-866]
    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [patched_1.10.2.jar:git-Paper-866]
    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558) [patched_1.10.2.jar:git-Paper-866]
    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.EntityMonster.damageEntity(EntityMonster.java:48) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.Entity.U(Entity.java:393) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:185) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.EntityInsentient.U(EntityInsentient.java:181) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.Entity.m(Entity.java:322) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:241) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.EntityMonster.m(EntityMonster.java:32) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.World.g(World.java:1713) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1530) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:867) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) [patched_1.10.2.jar:git-Paper-866]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-866]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
    at fr.neatmonster.nocheatplus.hooks.NCPExemptionManager.exemptPermanently(NCPExemptionManager.java:132) ~[?:?]
    at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:44) ~[?:?]
    at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:73) ~[?:?]
    at com.projectkorra.projectkorra.firebending.FireDamageTimer.dealFlameDamage(FireDamageTimer.java:58) ~[?:?]
    at com.projectkorra.projectkorra.PKListener.onEntityDamageEvent(PKListener.java:421) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1203.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-866]
    ... 27 more
```

**Comment by StrangeOne101** [comment]
Thanks for reporting. I'll fix that shortly.
