### ISSUE TITLE
NullPointerException in SurgeWall.returnWater

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#644]
```
[11:48:11] [Server thread/WARN]: java.lang.NullPointerException
[11:48:11] [Server thread/WARN]:    at com.projectkorra.projectkorra.waterbending.WaterReturn.<init>(WaterReturn.java:40)
[11:48:11] [Server thread/WARN]:    at com.projectkorra.projectkorra.waterbending.SurgeWall.returnWater(SurgeWall.java:453)
[11:48:11] [Server thread/WARN]:    at com.projectkorra.projectkorra.waterbending.SurgeWall.remove(SurgeWall.java:323)
[11:48:11] [Server thread/WARN]:    at com.projectkorra.projectkorra.waterbending.SurgeWall.progress(SurgeWall.java:214)
[11:48:11] [Server thread/WARN]:    at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:194)
[11:48:11] [Server thread/WARN]:    at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:108)
[11:48:11] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[11:48:11] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355)
[11:48:11] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:792)
[11:48:11] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[11:48:11] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
[11:48:11] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
[11:48:11] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by PhanaticD** [comment]
Also occurs with octopus, probably related

```
[12:14:56] [Server thread/WARN]: java.lang.NullPointerException
[12:14:56] [Server thread/WARN]:    at com.projectkorra.projectkorra.waterbending.WaterReturn.<init>(WaterReturn.java:40)
[12:14:56] [Server thread/WARN]:    at com.projectkorra.projectkorra.waterbending.OctopusForm.returnWater(OctopusForm.java:447)
[12:14:56] [Server thread/WARN]:    at com.projectkorra.projectkorra.waterbending.OctopusForm.remove(OctopusForm.java:428)
[12:14:56] [Server thread/WARN]:    at com.projectkorra.projectkorra.waterbending.OctopusForm.progress(OctopusForm.java:190)
[12:14:56] [Server thread/WARN]:    at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:194)
[12:14:56] [Server thread/WARN]:    at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:108)
[12:14:56] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[12:14:56] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355)
[12:14:56] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:792)
[12:14:56] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[12:14:56] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
[12:14:56] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
[12:14:56] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by PhanaticD** [comment]
this issue is still present in 1.8.2 latest version
```
[06:59:05 WARN]: java.lang.NullPointerException
[06:59:05 WARN]:        at com.projectkorra.projectkorra.waterbending.util.WaterReturn.<init>(WaterReturn.java:44)
[06:59:05 WARN]:        at com.projectkorra.projectkorra.waterbending.SurgeWall.returnWater(SurgeWall.java:447)
[06:59:05 WARN]:        at com.projectkorra.projectkorra.waterbending.SurgeWall.remove(SurgeWall.java:321)
[06:59:05 WARN]:        at com.projectkorra.projectkorra.waterbending.SurgeWall.progress(SurgeWall.java:213)
[06:59:05 WARN]:        at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:224)
[06:59:05 WARN]:        at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:108)
[06:59:05 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[06:59:05 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355)
[06:59:05 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:811)
[06:59:05 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[06:59:05 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749)
[06:59:05 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648)
[06:59:05 WARN]:        at java.lang.Thread.run(Thread.java:745)
```
