### ISSUE TITLE
NullPointerException PlayerToggleSneakEvent

### ISSUE THREAD

**Issue by Darius25** [ProjectKorra/ProjectKorra#787]
[00:25:19] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.8.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1416) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PacketPlayInEntityAction.a(SourceFile:43) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PacketPlayInEntityAction.a(SourceFile:9) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException

**Comment by OmniCypher-** [comment]
This error is from an old version of ProjectKorra. We currently have version `1.8.4` released and `1.8.5` on the way. I would highly recommend you update to `1.8.4` and see if this issue persists.
