### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#830]
```
[11:18:48 WARN]: java.lang.NullPointerException
[11:18:48 WARN]:        at com.projectkorra.projectkorra.GeneralMethods.displayMovePreview(GeneralMethods.java:663)
[11:18:48 WARN]:        at com.projectkorra.projectkorra.GeneralMethods.displayMovePreview(GeneralMethods.java:658)
[11:18:48 WARN]:        at com.projectkorra.projectkorra.chiblocking.WarriorStance.remove(WarriorStance.java:64)
[11:18:48 WARN]:        at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:232)
[11:18:48 WARN]:        at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:110)
[11:18:48 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[11:18:48 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[11:18:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832)
[11:18:48 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[11:18:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[11:18:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[11:18:48 WARN]:        at java.lang.Thread.run(Thread.java:745)
```
```
[11:20:46 WARN]: [ProjectKorra] Task #231 for ProjectKorra v1.8.6 generated an exception
java.lang.NullPointerException: null
        at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:211) ~[?:?]
        at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[?:?]
        at com.projectkorra.projectkorra.ability.util.CollisionManager.access$000(CollisionManager.java:36) ~[?:?]
        at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:204) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1168]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1168]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
 ```
```
[11:22:27 WARN]: [ProjectKorra] Task #290909 for ProjectKorra v1.8.6 generated an exception
java.lang.NullPointerException: null
        at com.projectkorra.projectkorra.firebending.combo.FireComboStream.collision(FireComboStream.java:116) ~[?:?]
        at com.projectkorra.projectkorra.firebending.combo.FireComboStream.run(FireComboStream.java:96) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1168]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1168]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```
```
[11:33:28] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1168]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1168]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1168]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.jar:git-Paper-1168]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1482) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1168]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1168]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_111]
    at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:1.8.0_111]
    at com.projectkorra.projectkorra.util.TempBlock.<init>(TempBlock.java:41) ~[?:?]
    at com.projectkorra.projectkorra.waterbending.OctopusForm.form(OctopusForm.java:171) ~[?:?]
    at com.projectkorra.projectkorra.waterbending.OctopusForm.form(OctopusForm.java:152) ~[?:?]
    at com.projectkorra.projectkorra.PKListener.onPlayerSneak(PKListener.java:1310) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor843.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1168]
    ... 16 more
```

**Comment by PhanaticD** [comment]
these are all as of https://github.com/ProjectKorra/ProjectKorra/commit/2fd66d7fbedf71cc18e966498c617ee267f25b49

**Comment by StrangeOne101** [comment]
I've seen quite a few of these pop up. I should have fixed one, but the rest of them seem to be a threading issue with collisions (like an ability is registered to CoreAbility with `super(player)` but the collision system is trying to detect collisions for them before they have finished calling the constructor). Just a theory, though. It's not my field of expertise.

**Comment by 0ct0ber** [comment]
Are you 100% sure you got your ProjectKorra jar from an official source? The second error trace would have been caused by a very strange issue outside of ProjectKorra (in either Java or ConcurrentHashMap)...

**Comment by PhanaticD** [comment]
this is very old report, im part of project korra staff now so ill be attempting to fix ones that I come across now instead :P
