### ISSUE TITLE
NPE octopus

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#868]
```
[12:36:52 ERROR]: Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1246]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1246]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1246]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.2.jar:git-Paper-1246]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.2.jar:git-Paper-1246]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1524) ~[patched_1.12.2.jar:git-Paper-1246]
        at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43) ~[patched_1.12.2.jar:git-Paper-1246]
        at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9) ~[patched_1.12.2.jar:git-Paper-1246]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1246]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1246]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1246]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1246]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1246]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1246]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_111]
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:1.8.0_111]
        at com.projectkorra.projectkorra.util.TempBlock.<init>(TempBlock.java:41) ~[?:?]
        at com.projectkorra.projectkorra.waterbending.OctopusForm.form(OctopusForm.java:171) ~[?:?]
        at com.projectkorra.projectkorra.waterbending.OctopusForm.form(OctopusForm.java:152) ~[?:?]
        at com.projectkorra.projectkorra.PKListener.onPlayerSneak(PKListener.java:1324) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor863.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1246]
        ... 16 more

```

**Comment by 0ct0ber** [comment]
Thanks for putting up these issues, I'll fix them in a patch :)
