### ISSUE TITLE
Null and CastClassException exception in PKListener onEntityDamageEvent

### ISSUE THREAD

**Issue by 0ct0ber** [ProjectKorra/ProjectKorra#872]
On a server I'm a part of, there's this exception occuring on the EntityDamageByBlockEvent, in line 473 of PKListener. 

It seems that this is caused due to CraftItem being casted to LivingEntity?
[spoiler="Stack Trace"]Could not pass event EntityDamageByBlockEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:507) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:631) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:617) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.EntityItem.damageEntity(EntityItem.java:256) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.BlockCactus.a(BlockCactus.java:94) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:961) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:542) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.EntityItem.B_(EntityItem.java:86) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftItem cannot be cast to org.bukkit.entity.LivingEntity
        at com.projectkorra.projectkorra.PKListener.onEntityDamageEvent(PKListener.java:473) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        ... 21 more[/spoiler]

**Comment by ChristopherWMM** [comment]
Resolved in the latest wip version.
