### ISSUE TITLE
error

### ISSUE THREAD

**Issue by poma123** [ProjectKorra/ProjectKorra#875]
```
07.01 19:05:56 [Server] ERROR Could not pass event EntityDamageByBlockEvent to ProjectKorra v1.8.6
07.01 19:05:56 [Server] INFO org.bukkit.event.EventException: null
07.01 19:05:56 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:492) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:632) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:618) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.EntityItem.damageEntity(EntityItem.java:267) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.burnFromLava(Entity.java:513) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.Y(Entity.java:466) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.B_(Entity.java:339) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.EntityItem.B_(EntityItem.java:70) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:913) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
07.01 19:05:56 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftItem cannot be cast to org.bukkit.entity.LivingEntity
07.01 19:05:56 [Server] INFO at com.projectkorra.projectkorra.PKListener.onEntityDamageEvent(PKListener.java:473) ~[?:?]
07.01 19:05:56 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor294.execute(Unknown Source) ~[?:?]
07.01 19:05:56 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1293]
07.01 19:05:56 [Server] INFO ... 22 more
```

**Comment by poma123** [comment]
#872

**Comment by ChristopherWMM** [comment]
Resolved in the latest wip version.
