### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by 0ct0ber** [ProjectKorra/ProjectKorra#879]
An error occurred on my test spigot 1.8.8 server, in onEnable() in the ProjectKorra general class, line 57. No such field was found for NETHER_WART_BLOCK.

Fix: Separate materials for different server versions

Log:

[19:46:12 ERROR]: Error occurred while enabling ProjectKorra v1.8.6 (Is it up to date?)
java.lang.NoSuchFieldError: NETHER_WART_BLOCK
	at com.projectkorra.projectkorra.GeneralMethods.<clinit>(GeneralMethods.java:145) ~[?:?]
	at com.projectkorra.projectkorra.ProjectKorra.onEnable(ProjectKorra.java:57) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.base/java.lang.Thread.run(Thread.java:844) [?:?]

**Comment by jayoevans** [comment]
ProjectKorra v1.8.6 is not compatible with Spigot v1.8.8. Please upgrade your server version to 1.9 or higher.

**Comment by 0ct0ber** [comment]
Then why does it say Tested Versions: 1.7, 1.8, 1.9, 1.10, 1.11, 1.12 on spigot?

https://www.spigotmc.org/resources/projectkorra-core.2734/

**Comment by 0ct0ber** [comment]
Will there be any attempt to make the plugin support multiple versions?

**Comment by jayoevans** [comment]
Apologies, that's an issue with the Spigot page not being updated. I've contacted the administrators to get it updated. We do not plan to continue updating versions below 1.9 for multiple reasons on the backend. If you wish to use this version of Spigot still you will need to downgrade to an earlier version of ProjectKorra. For our version history, please visit http://projectkorra.com/forum/resources/projectkorra-core.1/history

**Comment by RoboMWM** [comment]
In addition, the projectkorra version listed there is 1.8.4, not 1.8.6.

**Comment by 0ct0ber** [comment]
It turns out that aside, the error caused here was actually due to a mistake in the code (although the same error would occur for another thing if this error didn't pop up). I'm sort of new to GitHub, and tried editing the branch then clicking the propose code changes button, but this didn't show up in the pull requests?

Do pull requests need to be made by doing Edit > Propose Code Changes, or Pull Requests > New Pull Request?

**Comment by ChristopherWMM** [comment]
Thanks @0ct0ber for pointing out the incorrect information on the spigot page! Everything has been cleared up so all information should be current aside from the latest build.
