### ISSUE TITLE
error during avatarstate

### ISSUE THREAD

**Issue by poma123** [ProjectKorra/ProjectKorra#887]
```
13.01 20:38:35 [Server] ERROR Could not pass event PlayerAnimationEvent to ProjectKorra v1.8.6
13.01 20:38:35 [Server] INFO org.bukkit.event.EventException: null
13.01 20:38:35 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1515) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:24) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:5) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
13.01 20:38:35 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
13.01 20:38:35 [Server] INFO Caused by: java.lang.NullPointerException: Name is null
13.01 20:38:35 [Server] INFO at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.8.0_151]
13.01 20:38:35 [Server] INFO at org.bukkit.Sound.valueOf(Sound.java:11) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO at com.projectkorra.projectkorra.ability.AvatarAbility.playAvatarSound(AvatarAbility.java:39) ~[?:?]
13.01 20:38:35 [Server] INFO at com.projectkorra.projectkorra.avatar.AvatarState.<init>(AvatarState.java:62) ~[?:?]
13.01 20:38:35 [Server] INFO at com.projectkorra.projectkorra.PKListener.onPlayerSwing(PKListener.java:1714) ~[?:?]
13.01 20:38:35 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor440.execute(Unknown Source) ~[?:?]
13.01 20:38:35 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1293]
13.01 20:38:35 [Server] INFO ... 16 more
```

**Comment by Simplicitee** [comment]
Your sound seems to be causing problems, check to see if you have it spelled right and that the sound exists in your Minecraft version

**Comment by poma123** [comment]
Which sound?

**Comment by xNuminousx** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

You can use any sound you want. But the default is BLOCK_ANCIL_[something] I don't recall which anvil version it is.

**Comment by Simplicitee** [comment]
In the config under the AvatarState ability

**Comment by ChristopherWMM** [comment]
Thanks @xNuminousx and @Simplicitee, marking as resolved.
