### ISSUE TITLE
error with /projectkorra reload

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#897]
not sure what causes this

```
[07:51:00 WARN]: Unexpected exception while parsing console command "projectkorra reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'projectkorra' in plugin ProjectKorra v1.8.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:640) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:464) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.projectkorra.projectkorra.ability.util.ComboManager.addRequirement(ComboManager.java:259) ~[?:?]
        at com.projectkorra.projectkorra.ability.util.ComboManager.<init>(ComboManager.java:42) ~[?:?]
        at com.projectkorra.projectkorra.GeneralMethods.reloadPlugin(GeneralMethods.java:1607) ~[?:?]
        at com.projectkorra.projectkorra.command.ReloadCommand.execute(ReloadCommand.java:25) ~[?:?]
        at com.projectkorra.projectkorra.command.Commands$1.onCommand(Commands.java:131) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1322]
        ... 8 more
```

**Comment by xNuminousx** [comment]
Probably because Pk doesn't work with MC 1.12.2 very well. I know there have been reports on the forums about it breaking somehow when using that version. Worth a test though.

**Comment by plushmonkey** [comment]
It's because the ComboManager is initialized in the reload method during the time when no abilities are registered. Abilities are cleared in stopBending, then ComboManager is initialized, then abilities are registered again. ComboManager calls getAbility in its constructor, which will return null because no abilities are registered.

**Comment by Simplicitee** [comment]
This is already known and being fixed

**Comment by Simplicitee** [comment]
This is fixed

**Comment by ChristopherWMM** [comment]
Resolved as of https://github.com/ProjectKorra/ProjectKorra/commit/9fb403b788b75ec61e0bd654d9e46945aba0d3fd.
