### ISSUE TITLE
NPE with new earthgrab

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#898]
```
[07:49:35] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1322]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1322]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1322]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1322]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1322]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1530) ~[patched_1.12.2.jar:git-Paper-1322]
    at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43) ~[patched_1.12.2.jar:git-Paper-1322]
    at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9) ~[patched_1.12.2.jar:git-Paper-1322]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1322]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1322]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1322]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1322]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1322]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1322]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
    at com.projectkorra.projectkorra.earthbending.EarthGrab.remove(EarthGrab.java:241) ~[?:?]
    at com.projectkorra.projectkorra.ability.CoreAbility.start(CoreAbility.java:145) ~[?:?]
    at com.projectkorra.projectkorra.earthbending.EarthGrab.<init>(EarthGrab.java:75) ~[?:?]
    at com.projectkorra.projectkorra.PKListener.onPlayerSneak(PKListener.java:1406) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor858.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1322]
    ... 16 more
```

**Comment by PhanaticD** [comment]
another error possibly related:
```
[08:40:23 ERROR]: Could not pass event EntityDamageByEntityEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1322]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:581) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:484) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:613) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1367) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:853) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:887) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:603) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1021) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1352) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1703) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1322]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.projectkorra.projectkorra.earthbending.EarthGrab.remove(EarthGrab.java:241) ~[?:?]
        at com.projectkorra.projectkorra.PKListener.onEntityDamageEvent(PKListener.java:479) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor849.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1322]
        ... 27 more

```

**Comment by PhanaticD** [comment]
also related:
```
[08:52:20 WARN]: java.lang.NullPointerException
[08:52:20 WARN]:        at com.projectkorra.projectkorra.earthbending.EarthGrab.remove(EarthGrab.java:241)
[08:52:20 WARN]:        at com.projectkorra.projectkorra.earthbending.EarthGrab.progress(EarthGrab.java:105)
[08:52:20 WARN]:        at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:234)
[08:52:20 WARN]:        at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:110)
[08:52:20 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[08:52:20 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[08:52:20 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[08:52:20 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[08:52:20 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[08:52:20 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[08:52:20 WARN]:        at java.lang.Thread.run(Thread.java:745)
[08:52:20 WARN]: java.lang.NullPointerException
[08:52:20 WARN]:        at com.projectkorra.projectkorra.earthbending.EarthGrab.remove(EarthGrab.java:241)
[08:52:20 WARN]:        at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:239)
[08:52:20 WARN]:        at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:110)
[08:52:20 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[08:52:20 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[08:52:20 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[08:52:20 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[08:52:20 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[08:52:20 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[08:52:20 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Simplicitee** [comment]
I have no clue how you could possibly be creating this error

**Comment by PhanaticD** [comment]
well im not creating it on purpose lol was in my logs

**Comment by Simplicitee** [comment]
I need to know exact causes for this case, the error and code provide little help as to what's wrong
