### ISSUE TITLE
NPE with FireManipulation

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#899]
```
[08:10:43 WARN]: Task #117 for ProjectKorra v1.8.6 generated an exception
java.lang.NullPointerException: null
        at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:218) ~[?:?]
        at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[?:?]
        at com.projectkorra.projectkorra.ability.util.CollisionManager.access$000(CollisionManager.java:36) ~[?:?]
        at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:204) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Simplicitee** [comment]
Do you have anymore information on this?
