### ISSUE TITLE
HorizontalVelocityChangeEvent  error

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#900]
```
[08:24:07 ERROR]: Could not pass event HorizontalVelocityChangeEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1322]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1322]
        at com.projectkorra.projectkorra.object.HorizontalVelocityTracker.update(HorizontalVelocityTracker.java:94) [ProjectKorra.jar:?]
        at com.projectkorra.projectkorra.object.HorizontalVelocityTracker.updateAll(HorizontalVelocityTracker.java:107) [ProjectKorra.jar:?]
        at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:115) [ProjectKorra.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:88) ~[?:?]
        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:96) ~[?:?]
        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:100) ~[?:?]
        at com.projectkorra.projectkorra.PKListener.onHorizontalCollision(PKListener.java:689) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor850.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1322]
        ... 14 more

```

**Comment by PhanaticD** [comment]
probably related:
```
[12:36:37 WARN]: java.lang.NullPointerException
[12:36:37 WARN]:        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:88)
[12:36:37 WARN]:        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:96)
[12:36:37 WARN]:        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:100)
[12:36:37 WARN]:        at com.projectkorra.projectkorra.airbending.AirBlast.affect(AirBlast.java:268)
[12:36:37 WARN]:        at com.projectkorra.projectkorra.airbending.AirBlast.progress(AirBlast.java:427)
[12:36:37 WARN]:        at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:234)
[12:36:37 WARN]:        at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:110)
[12:36:37 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[12:36:37 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[12:36:37 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[12:36:37 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[12:36:37 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[12:36:37 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[12:36:37 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by PhanaticD** [comment]
fixed in https://github.com/ProjectKorra/ProjectKorra/pull/909
