### ISSUE TITLE
NPE statistic name

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#901]
```
[08:50:43 ERROR]: Could not pass event PlayerDeathEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1322]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:414) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:449) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:603) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:204) [patched_1.12.2.jar:git-Paper-1322]
        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:68) [ProjectKorra.jar:?]
        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:96) [ProjectKorra.jar:?]
        at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:100) [ProjectKorra.jar:?]
        at com.jedk1.jedcore.ability.avatar.elementsphere.ESEarth.progress(ESEarth.java:84) [JedCore.jar:?]
        at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:234) [ProjectKorra.jar:?]
        at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:110) [ProjectKorra.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.projectkorra.projectkorra.util.Statistic.getStatisticName(Statistic.java:10) ~[?:?]
        at com.projectkorra.projectkorra.util.StatisticsMethods.addStatisticAbility(StatisticsMethods.java:43) ~[?:?]
        at com.projectkorra.projectkorra.PKListener.onPlayerDeath(PKListener.java:974) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor864.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1322]
        ... 23 more

```

**Comment by PhanaticD** [comment]
fixed in https://github.com/ProjectKorra/ProjectKorra/pull/911
