### ISSUE TITLE
NPE in /b who

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#902]
```
[09:21:46 INFO]: Flozaro issued server command: /b who Super_MLG_Pro
[09:21:46 WARN]: Plugin ProjectKorra v1.8.6 generated an exception while executing task 507060
java.lang.NullPointerException: null
        at com.projectkorra.projectkorra.command.WhoCommand.whoPlayer(WhoCommand.java:360) ~[?:?]
        at com.projectkorra.projectkorra.command.WhoCommand.access$100(WhoCommand.java:39) ~[?:?]
        at com.projectkorra.projectkorra.command.WhoCommand$2.run(WhoCommand.java:190) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1322]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1322]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by 0ct0ber** [comment]
I can confirm that NPEs do indeed occur, specifically when checking offline players with /bending who.

**Comment by ChristopherWMM** [comment]
Fixed on my local branch, PR inbound.
