### ISSUE TITLE
octopus NPE

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#904]
```
[12:38:13 ERROR]: Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1322]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1530) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:43) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PacketPlayInEntityAction.a(SourceFile:9) ~[patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1322]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_111]
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:1.8.0_111]
        at com.projectkorra.projectkorra.util.TempBlock.<init>(TempBlock.java:41) ~[?:?]
        at com.projectkorra.projectkorra.waterbending.OctopusForm.form(OctopusForm.java:171) ~[?:?]
        at com.projectkorra.projectkorra.waterbending.OctopusForm.form(OctopusForm.java:152) ~[?:?]
        at com.projectkorra.projectkorra.PKListener.onPlayerSneak(PKListener.java:1344) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor858.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1322]
        ... 16 more

```
looks like this is still here

**Comment by 0ct0ber** [comment]
@PhanaticD You had said to me that you were going to be resolving your own issues... do you plan on fixing these, or should I resolve them?

**Comment by PhanaticD** [comment]
you are welcome to get to it first, I posted it here for anyone including myself

**Comment by PhanaticD** [comment]
fixed here: https://github.com/ProjectKorra/ProjectKorra/pull/910
