### ISSUE TITLE
Errors with disabled moves?

### ISSUE THREAD

**Issue by Loonyy** [ProjectKorra/ProjectKorra#924]
(Can't pastebin cause used daily limit)
On the latest WIP, if you replace a default move and disable it, there's an error that appears when you activate the move. For instance, having the Combustion addon and disabling the default Combustion.

I've re-created this with other moves aswell.
```19.03 03:45:50 [Server] ERROR Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.8.6
19.03 03:45:50 [Server] INFO org.bukkit.event.EventException
19.03 03:45:50 [Server] INFO at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:79) ~[?:?]
19.03 03:45:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1402) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInEntityAction.a(SourceFile:43) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInEntityAction.a(SourceFile:9) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
19.03 03:45:50 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 03:45:50 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
19.03 03:45:50 [Server] INFO Caused by: java.lang.NullPointerException
19.03 03:45:50 [Server] INFO at com.projectkorra.projectkorra.firebending.combustion.Combustion.<init>(Combustion.java:40) ~[?:?]
19.03 03:45:50 [Server] INFO at com.projectkorra.projectkorra.PKListener.onPlayerSneak(PKListener.java:1436) ~[?:?]
19.03 03:45:50 [Server] INFO at sun.reflect.GeneratedMethodAccessor330.invoke(Unknown Source) ~[?:?]
19.03 03:45:50 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
19.03 03:45:50 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
19.03 03:45:50 [Server] INFO at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:69) ~[?:?]
19.03 03:45:50 [Server] INFO ... 15 more```

**Comment by Varhagna** [comment]
I'm closing this issue since it has been two years and any of your error logs will not be able to help us given the amount of code that has changed since now and then. Feel free to recreate your issue with updated error logs as well as a PK Debug. Thank you
