### ISSUE TITLE
FireManip collisions error

### ISSUE THREAD

**Issue by Loonyy** [ProjectKorra/ProjectKorra#925]
(Can't pastebin_

```19.03 04:02:56 [Server] WARN [ProjectKorra] Task #452 for ProjectKorra v1.8.6 generated an exception
19.03 04:02:56 [Server] INFO java.lang.NullPointerException
19.03 04:02:56 [Server] INFO at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:218) ~[ProjectKorra-1.8.6.jar:?]
19.03 04:02:56 [Server] INFO at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[ProjectKorra-1.8.6.jar:?]
19.03 04:02:56 [Server] INFO at com.projectkorra.projectkorra.ability.util.CollisionManager.access$0(CollisionManager.java:69) ~[ProjectKorra-1.8.6.jar:?]
19.03 04:02:56 [Server] INFO at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:204) ~[ProjectKorra-1.8.6.jar:?]
19.03 04:02:56 [Server] INFO at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56) ~[MassiveLag.jar:?]
19.03 04:02:56 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
19.03 04:02:56 [Server] WARN [ProjectKorra] Task #452 for ProjectKorra v1.8.6 generated an exception
19.03 04:02:56 [Server] INFO java.lang.NullPointerException
19.03 04:02:56 [Server] INFO at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:218) ~[ProjectKorra-1.8.6.jar:?]
19.03 04:02:56 [Server] INFO at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[ProjectKorra-1.8.6.jar:?]
19.03 04:02:56 [Server] INFO at com.projectkorra.projectkorra.ability.util.CollisionManager.access$0(CollisionManager.java:69) ~[ProjectKorra-1.8.6.jar:?]
19.03 04:02:56 [Server] INFO at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:204) ~[ProjectKorra-1.8.6.jar:?]
19.03 04:02:56 [Server] INFO at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56) ~[MassiveLag.jar:?]
19.03 04:02:56 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-f709362]
19.03 04:02:56 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
19.03 04:02:56 [Server] WARN [ProjectKorra] Task #452 for ProjectKorra v1.8.6 generated an exception
19.03 04:02:56 [Server] INFO java.lang.NullPointerException
19.03 04:03:01 [Multicraft] Skipped 68 lines due to rate limit (30/s)```

**Comment by xNuminousx** [comment]
Is this on WIP build? I see it says v1.8.6 but I'm unaware if the WIP build has a different version number.

**Comment by Loonyy** [comment]
Yep

**Comment by PhanaticD** [comment]
I have had this as well, but I am having a very hard time tracking it down

**Comment by Loonyy** [comment]
Well the errors are on these lines:
FireManipulation.getLocations(FireManipulation.java:218) ~
`locations.addAll(points.keySet());`

CollisionManager.detectCollisions(CollisionManager.java:104) ~
`locationsCache.put(abilityFirst, abilityFirst.getLocations());`

CollisionManager.access$0(CollisionManager.java:69) ~
```private void detectCollisions() {
		int activeInstanceCount = 0;
		
		for (CoreAbility ability : CoreAbility.getAbilitiesByInstances()) {
			if (!(ability instanceof PassiveAbility)) {
				if (++activeInstanceCount > 1) {
					break;
				}
			}
		}
		
		if (activeInstanceCount <= 1) {
			return;
		}```

**Comment by plushmonkey** [comment]
It's because the points map is only initialized for the shift type in setFields. Activating it with click will start an instance that has null points map, resulting in NullPointerException when the collision system runs.

Punch activate it without sneaking to trigger it.

**Comment by PhanaticD** [comment]
would anyone disagree that the best fix is to just return an empty set of points? either that or the collision manager will need to check the firemanipulation click type

**Comment by Loonyy** [comment]
There was supposed to be a click version of FireManip but it was never finished

**Comment by Varhagna** [comment]
I'm closing this issue since it has been two years and any of your error logs will not be able to help us given the amount of code that has changed since now and then. Feel free to recreate your issue with updated error logs as well as a PK Debug. Thank you
