### ISSUE TITLE
SurgeWall remove - NullPointerException

### ISSUE THREAD

**Issue by poma123** [ProjectKorra/ProjectKorra#930]
```
08.04 16:52:34 [Server] WARN java.lang.NullPointerException
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.waterbending.util.WaterReturn.<init>(WaterReturn.java:44)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.waterbending.SurgeWall.returnWater(SurgeWall.java:453)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.waterbending.SurgeWall.remove(SurgeWall.java:322)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.waterbending.SurgeWall.progress(SurgeWall.java:214)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:227)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:110)
08.04 16:52:34 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
08.04 16:52:34 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
08.04 16:52:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
08.04 16:52:34 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
08.04 16:52:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
08.04 16:52:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
08.04 16:52:34 [Server] WARN at java.lang.Thread.run(Thread.java:748)
08.04 16:52:34 [Server] WARN java.lang.NullPointerException
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.waterbending.util.WaterReturn.<init>(WaterReturn.java:44)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.waterbending.SurgeWall.returnWater(SurgeWall.java:453)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.waterbending.SurgeWall.remove(SurgeWall.java:322)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:232)
08.04 16:52:34 [Server] WARN at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:110)
08.04 16:52:34 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
08.04 16:52:34 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
08.04 16:52:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
08.04 16:52:34 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
08.04 16:52:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
08.04 16:52:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
08.04 16:52:34 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Comment by xNuminousx** [comment]
Use Spigot, not Bukkit. ProjectKorra only works with Spigot.

**Comment by poma123** [comment]
I'm using PaperSpigot.

**Comment by xNuminousx** [comment]
Hmm... Not sure of the differences between that and Spigot so not sure how Pk would interact with it.

**Comment by Loonyy** [comment]
The PK server uses PaperSpigot.

**Comment by Varhagna** [comment]
Resolved.
