### ISSUE TITLE
Could not pass event BlockPlaceEvent to ProjectKorra v1.8.8 for MC 1.13.2+

### ISSUE THREAD

**Issue by andris155** [ProjectKorra/ProjectKorra#995]
```
[11:07:13] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to ProjectKorra v1.8.8 for MC 1.13.2+
java.lang.IllegalArgumentException: Cannot get data for not block FLINT_AND_STEEL
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData.newData(CraftBlockData.java:492) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createBlockData(CraftServer.java:1998) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createBlockData(CraftServer.java:1973) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1420) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.Material.createBlockData(Material.java:3060) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setType(CraftBlock.java:144) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setType(CraftBlock.java:138) ~[patched_1.13.2.jar:git-Paper-638]
	at com.projectkorra.projectkorra.PKListener.onBlockPlace(PKListener.java:273) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor923.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-638]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:199) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:237) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:537) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1348) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-638]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-638]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
Paper 1.13.2

**Comment by PhanaticD** [comment]
this was fixed already, you can compile the 1.13 branch to get latest changes
