### ISSUE TITLE
Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.8.8 for MC 1.13.2+

### ISSUE THREAD

**Issue by andris155** [ProjectKorra/ProjectKorra#996]
```
[14:50:32] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to ProjectKorra v1.8.8 for MC 1.13.2+
java.lang.NoClassDefFoundError: com/projectkorra/projectkorra/util/ParticleEffect$ParticleData
	at com.Pride.korra.AirCoccoon.CocoonListener.onSneak(CocoonListener.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor866.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-638]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1840) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PacketPlayInEntityAction.a(SourceFile:43) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PacketPlayInEntityAction.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-638]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-638]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.projectkorra.projectkorra.util.ParticleEffect$ParticleData
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 18 more
```
Paper 1.13.2

**Comment by FinnBueno** [comment]
This appears to be an issue with the custom ability AirCoccoon. I believe it's attempting to call upon old code that has been removed from ProjectKorra, which it cannot find. Removing this ability will solve this issue. If you want this ability updated, you should ask the developer to update it.

Please note that we do not take responsibility for custom abilities, nor do we provide support for them. Therefor, we will not and cannot fix this issue ourselves.
