### ISSUE TITLE
Non [a-z0-9/._-] character in path of location: minecraft:BLOCK_WOODEN_DOOR_CLOSE

### ISSUE THREAD

**Issue by andris155** [ProjectKorra/ProjectKorra#997]
```
[21:51:22] [Server thread/WARN]: net.minecraft.server.v1_13_R2.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:BLOCK_WOODEN_DOOR_CLOSE
[21:51:22] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftKey.<init>(SourceFile:38)
[21:51:22] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftKey.<init>(SourceFile:43)
[21:51:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.playSound(CraftWorld.java:1679)
[21:51:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.playSound(CraftWorld.java:1657)
[21:51:22] [Server thread/WARN]: 	at com.projectkorra.projectkorra.airbending.AirSuction.handleDoorMechanics(AirSuction.java:160)
[21:51:22] [Server thread/WARN]: 	at com.projectkorra.projectkorra.airbending.AirSuction.advanceLocation(AirSuction.java:106)
[21:51:22] [Server thread/WARN]: 	at com.projectkorra.projectkorra.airbending.AirSuction.progress(AirSuction.java:244)
[21:51:22] [Server thread/WARN]: 	at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:251)
[21:51:22] [Server thread/WARN]: 	at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:105)
[21:51:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[21:51:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[21:51:22] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[21:51:22] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:51:22] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[21:51:22] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[21:51:22] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[21:51:22] [Server thread/ERROR]: com.projectkorra.projectkorra.airbending.AirSuction@273d1a06[
  affectedDoors=[]
  progressing=true
  particleCount=6
  cooldown=500
  speed=25.0
  range=20.0
  radius=2.0
  pushFactor=2.5
  random=java.util.Random@15cf876a
  location=Location{world=CraftWorld{name=world},x=-3718.2195474115497,y=48.30490893553754,z=-220.29382855988734,pitch=-47.85002,yaw=132.77003}
  origin=Location{world=CraftWorld{name=world},x=-3718.4289130886687,y=48.62000000476837,z=-220.48750001192093,pitch=-47.85002,yaw=132.77003}
  direction=0.49262512263780744,-0.7413907511363547,0.4556975341995576
  canAffectSelf=false
  player=CraftPlayer{name=KingDead}
  bPlayer=com.projectkorra.projectkorra.BendingPlayer@d721f3b[
  permaRemoved=false
  toggled=true
  tremorSense=true
  illumination=true
  chiBlocked=false
  slowTime=0
  player=CraftPlayer{name=KingDead}
  uuid=cc7f8628-9162-3262-9c9f-48552265aa2d
  name=KingDead
  stance=<null>
  cooldownManager=com.projectkorra.projectkorra.util.DBCooldownManager@3ee590a6
  elements=[Air]
  subelements=[]
  abilities={1=AirBlast, 2=AirShield, 3=Tornado, 4=AirSwipe, 5=AirScooter, 6=AirBlast, 7=AirShield, 8=Tornado, 9=AirSuction}
  cooldowns={AirSuction=com.projectkorra.projectkorra.util.Cooldown@7bd78239}
  toggledElements={Air=true, Fire=true, Earth=true, Water=true, Chi=true}
]
  flightHandler=com.projectkorra.projectkorra.util.FlightHandler@6e3d1ea9
  attributeModifiers={}
  attributeValues={}
  started=true
  removed=false
  hidden=false
  id=-2147062306
  startTime=1563047482380
  startTick=24945444
  attributesModified=true
]
```
Paper 1.13.2
ProjectKorra v1.8.8

**Comment by PhanaticD** [comment]
this was fixed already, you can compile the 1.13 branch to get latest changes
