### ISSUE TITLE
java.lang.NullPointerException projectkorra.waterbending.multiabilities

### ISSUE THREAD

**Issue by andris155** [ProjectKorra/ProjectKorra#998]
```
[21:11:31] [Server thread/WARN]: java.lang.NullPointerException
[21:11:31] [Server thread/WARN]: 	at com.projectkorra.projectkorra.waterbending.multiabilities.WaterArmsWhip.dragEntity(WaterArmsWhip.java:362)
[21:11:31] [Server thread/WARN]: 	at com.projectkorra.projectkorra.waterbending.multiabilities.WaterArmsWhip.progress(WaterArmsWhip.java:225)
[21:11:31] [Server thread/WARN]: 	at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:251)
[21:11:31] [Server thread/WARN]: 	at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:105)
[21:11:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[21:11:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[21:11:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[21:11:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:11:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[21:11:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[21:11:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[21:11:31] [Server thread/ERROR]: com.projectkorra.projectkorra.waterbending.multiabilities.WaterArmsWhip@4ab9bfc6[
  reverting=true
  hasDamaged=false
  grappled=true
  grabbed=true
  grappleRespectRegions=false
  usageCooldownEnabled=false
  whipLength=12
  whipLengthWeak=8
  whipLengthNight=16
  whipLengthFullMoon=20
  initLength=4
  punchLength=8
  punchLengthNight=11
  punchLengthFullMoon=13
  activeLength=12
  whipSpeed=1
  grabDuration=3500
  usageCooldown=200
  time=1563045094365
  pullMultiplier=0.15
  punchDamage=0.5
  playerHealth=20.0
  arm=LEFT
  ability=GRAB
  grabbedEntity=CraftPlayer{name=DrBoomer}
  end=<null>
  waterArms=com.projectkorra.projectkorra.waterbending.multiabilities.WaterArms@2f3deaa1[
  cooldownLeft=true
  cooldownRight=false
  fullSource=true
  leftArmConsumed=false
  rightArmConsumed=false
  canUsePlantSource=true
  lightningEnabled=true
  lightningKill=false
  lengthReduction=0
  initLength=4
  sourceGrabRange=12
  maxPunches=10
  maxIceBlasts=8
  maxUses=40
  selectedSlot=3
  freezeSlot=4
  cooldown=20000
  lastClickTime=0
  lightningDamage=10.0
  world=CraftWorld{name=world}
  sneakMsg=Aktív Képesség:
  activeArm=LEFT
  right=[CraftBlock{pos=BlockPosition{x=-4219, y=67, z=-220},type=WATER,data=Block{minecraft:water}[level=3],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$a@db44aa2[falling=false,level=5]}, CraftBlock{pos=BlockPosition{x=-4220, y=67, z=-220},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}, CraftBlock{pos=BlockPosition{x=-4220, y=66, z=-219},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}, CraftBlock{pos=BlockPosition{x=-4219, y=65, z=-219},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}, CraftBlock{pos=BlockPosition{x=-4219, y=65, z=-218},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}, CraftBlock{pos=BlockPosition{x=-4219, y=64, z=-218},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}]
  left=[CraftBlock{pos=BlockPosition{x=-4217, y=67, z=-222},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}, CraftBlock{pos=BlockPosition{x=-4217, y=66, z=-221},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}, CraftBlock{pos=BlockPosition{x=-4216, y=66, z=-221},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}, CraftBlock{pos=BlockPosition{x=-4216, y=65, z=-220},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}, CraftBlock{pos=BlockPosition{x=-4215, y=64, z=-220},type=WATER,data=Block{minecraft:water}[level=0],fluid=net.minecraft.server.v1_13_R2.FluidTypeWater$b@780ec4a5[falling=false]}]
  external=[com.projectkorra.projectkorra.util.TempBlock@685b945b, com.projectkorra.projectkorra.util.TempBlock@46195419, com.projectkorra.projectkorra.util.TempBlock@373e7938, com.projectkorra.projectkorra.util.TempBlock@4c860681, com.projectkorra.projectkorra.util.TempBlock@5a95349f, com.projectkorra.projectkorra.util.TempBlock@3999692, com.projectkorra.projectkorra.util.TempBlock@29484945, com.projectkorra.projectkorra.util.TempBlock@40a84db9, com.projectkorra.projectkorra.util.TempBlock@5cbccfad, com.projectkorra.projectkorra.util.TempBlock@7d671cc, com.projectkorra.projectkorra.util.TempBlock@23598e43, com.projectkorra.projectkorra.util.TempBlock@1a312a2a, com.projectkorra.projectkorra.util.TempBlock@524c9b50, com.projectkorra.projectkorra.util.TempBlock@696b38a, com.projectkorra.projectkorra.util.TempBlock@293e0b21, com.projectkorra.projectkorra.util.TempBlock@5f3ced3, com.projectkorra.projectkorra.util.TempBlock@142b010a, com.projectkorra.projectkorra.util.TempBlock@162ee00f, com.projectkorra.projectkorra.util.TempBlock@5755757, com.projectkorra.projectkorra.util.TempBlock@2d38ea1c, com.projectkorra.projectkorra.util.TempBlock@38d378f5, com.projectkorra.projectkorra.util.TempBlock@30a0f489, com.projectkorra.projectkorra.util.TempBlock@3266a64d, com.projectkorra.projectkorra.util.TempBlock@581adc2a, com.projectkorra.projectkorra.util.TempBlock@5be822db, com.projectkorra.projectkorra.util.TempBlock@6ddc74ef, com.projectkorra.projectkorra.util.TempBlock@36d044e3, com.projectkorra.projectkorra.util.TempBlock@3eb0e583, com.projectkorra.projectkorra.util.TempBlock@4ef58db, com.projectkorra.projectkorra.util.TempBlock@853b967, com.projectkorra.projectkorra.util.TempBlock@3c18402c, com.projectkorra.projectkorra.util.TempBlock@2dfd38cb, com.projectkorra.projectkorra.util.TempBlock@23809eb6, com.projectkorra.projectkorra.util.TempBlock@4d3dd204, com.projectkorra.projectkorra.util.TempBlock@497df744, com.projectkorra.projectkorra.util.TempBlock@6609d733, com.projectkorra.projectkorra.util.TempBlock@75a0d61, com.projectkorra.projectkorra.util.TempBlock@1171c14d, com.projectkorra.projectkorra.util.TempBlock@65ec5cd1, com.projectkorra.projectkorra.util.TempBlock@1524d71a, com.projectkorra.projectkorra.util.TempBlock@26c544fa, com.projectkorra.projectkorra.util.TempBlock@3ef860ba, com.projectkorra.projectkorra.util.TempBlock@32b3fcf0, com.projectkorra.projectkorra.util.TempBlock@7dfc1fbf, com.projectkorra.projectkorra.util.TempBlock@5480c5c4, com.projectkorra.projectkorra.util.TempBlock@16512914, com.projectkorra.projectkorra.util.TempBlock@29ea8d6, com.projectkorra.projectkorra.util.TempBlock@7a45040d, com.projectkorra.projectkorra.util.TempBlock@2bcc1186, com.projectkorra.projectkorra.util.TempBlock@1f123658, com.projectkorra.projectkorra.util.TempBlock@28738a39, com.projectkorra.projectkorra.util.TempBlock@4234da66, com.projectkorra.projectkorra.util.TempBlock@2168ab3b, com.projectkorra.projectkorra.util.TempBlock@3ed3df85, com.projectkorra.projectkorra.util.TempBlock@51cb4792, com.projectkorra.projectkorra.util.TempBlock@648e5ad3, com.projectkorra.projectkorra.util.TempBlock@65c8fc96, com.projectkorra.projectkorra.util.TempBlock@30cd5f93, com.projectkorra.projectkorra.util.TempBlock@47b42ad6, com.projectkorra.projectkorra.util.TempBlock@712eeb4d, com.projectkorra.projectkorra.util.TempBlock@6c0afa3, com.projectkorra.projectkorra.util.TempBlock@2aa084c6, com.projectkorra.projectkorra.util.TempBlock@571e9d76, com.projectkorra.projectkorra.util.TempBlock@5067fc0e, com.projectkorra.projectkorra.util.TempBlock@64148078, com.projectkorra.projectkorra.util.TempBlock@27d384bc, com.projectkorra.projectkorra.util.TempBlock@55c896a7, com.projectkorra.projectkorra.util.TempBlock@43b236dd, com.projectkorra.projectkorra.util.TempBlock@7f53881, com.projectkorra.projectkorra.util.TempBlock@3f411334, com.projectkorra.projectkorra.util.TempBlock@2db412cc, com.projectkorra.projectkorra.util.TempBlock@568d7ef5, com.projectkorra.projectkorra.util.TempBlock@64022379, com.projectkorra.projectkorra.util.TempBlock@25a71cdb, com.projectkorra.projectkorra.util.TempBlock@74312a4f, com.projectkorra.projectkorra.util.TempBlock@3a61e91f, com.projectkorra.projectkorra.util.TempBlock@769271ed, com.projectkorra.projectkorra.util.TempBlock@4fc47145, com.projectkorra.projectkorra.util.TempBlock@32485eca, com.projectkorra.projectkorra.util.TempBlock@851f9d6, com.projectkorra.projectkorra.util.TempBlock@b620ee5, com.projectkorra.projectkorra.util.TempBlock@2a77bcfe, com.projectkorra.projectkorra.util.TempBlock@11116498, com.projectkorra.projectkorra.util.TempBlock@45a70d1, com.projectkorra.projectkorra.util.TempBlock@172e87a3, com.projectkorra.projectkorra.util.TempBlock@636215ef, com.projectkorra.projectkorra.util.TempBlock@7241cdd5, com.projectkorra.projectkorra.util.TempBlock@76c30956, com.projectkorra.projectkorra.util.TempBlock@5f02399a, com.projectkorra.projectkorra.util.TempBlock@23711ce9, com.projectkorra.projectkorra.util.TempBlock@2a4d28d6, com.projectkorra.projectkorra.util.TempBlock@44de5d1, com.projectkorra.projectkorra.util.TempBlock@68f17d6f, com.projectkorra.projectkorra.util.TempBlock@e6ec1f0, com.projectkorra.projectkorra.util.TempBlock@4db2a812, com.projectkorra.projectkorra.util.TempBlock@717d00de, com.projectkorra.projectkorra.util.TempBlock@78faba59, com.projectkorra.projectkorra.util.TempBlock@360c13a9, com.projectkorra.projectkorra.util.TempBlock@2de8434d, com.projectkorra.projectkorra.util.TempBlock@3b0c29a9, com.projectkorra.projectkorra.util.TempBlock@48643fc2, com.projectkorra.projectkorra.util.TempBlock@5ecfd966, com.projectkorra.projectkorra.util.TempBlock@4cfbfe51, com.projectkorra.projectkorra.util.TempBlock@95819f2, com.projectkorra.projectkorra.util.TempBlock@7b3d3b97, com.projectkorra.projectkorra.util.TempBlock@7105b8ae, com.projectkorra.projectkorra.util.TempBlock@51ed2e40, com.projectkorra.projectkorra.util.TempBlock@70e8db58, com.projectkorra.projectkorra.util.TempBlock@357799c6, com.projectkorra.projectkorra.util.TempBlock@4554dee6, com.projectkorra.projectkorra.util.TempBlock@76f10642, com.projectkorra.projectkorra.util.TempBlock@13b6f805, com.projectkorra.projectkorra.util.TempBlock@6a5533e1, com.projectkorra.projectkorra.util.TempBlock@735098e4, com.projectkorra.projectkorra.util.TempBlock@6035b78d, com.projectkorra.projectkorra.util.TempBlock@77c1837b, com.projectkorra.projectkorra.util.TempBlock@7aa1a21b, com.projectkorra.projectkorra.util.TempBlock@30efea54, com.projectkorra.projectkorra.util.TempBlock@2e7100cd, com.projectkorra.projectkorra.util.TempBlock@dbdb19, com.projectkorra.projectkorra.util.TempBlock@5e682cab, com.projectkorra.projectkorra.util.TempBlock@187931ba, com.projectkorra.projectkorra.util.TempBlock@6d5eac9d, com.projectkorra.projectkorra.util.TempBlock@187059b3, com.projectkorra.projectkorra.util.TempBlock@68e17b26, com.projectkorra.projectkorra.util.TempBlock@3cf15536, com.projectkorra.projectkorra.util.TempBlock@483044a, com.projectkorra.projectkorra.util.TempBlock@73f7253c, com.projectkorra.projectkorra.util.TempBlock@7bf3193f, com.projectkorra.projectkorra.util.TempBlock@53ca1c06, com.projectkorra.projectkorra.util.TempBlock@20591094, com.projectkorra.projectkorra.util.TempBlock@6dcba11a, com.projectkorra.projectkorra.util.TempBlock@60bab06e, com.projectkorra.projectkorra.util.TempBlock@631b29cf, com.projectkorra.projectkorra.util.TempBlock@452fcbfb, com.projectkorra.projectkorra.util.TempBlock@53f08825, com.projectkorra.projectkorra.util.TempBlock@a7fa3a8, com.projectkorra.projectkorra.util.TempBlock@607524ad, com.projectkorra.projectkorra.util.TempBlock@287715af, com.projectkorra.projectkorra.util.TempBlock@78305beb, com.projectkorra.projectkorra.util.TempBlock@559c1947, com.projectkorra.projectkorra.util.TempBlock@4e7a14a1, com.projectkorra.projectkorra.util.TempBlock@5d57df8c, com.projectkorra.projectkorra.util.TempBlock@198a9257, com.projectkorra.projectkorra.util.TempBlock@686c5ab2, com.projectkorra.projectkorra.util.TempBlock@35055fda, com.projectkorra.projectkorra.util.TempBlock@6a30a3ef, com.projectkorra.projectkorra.util.TempBlock@245c1fbc, com.projectkorra.projectkorra.util.TempBlock@32974277, com.projectkorra.projectkorra.util.TempBlock@1e662282, com.projectkorra.projectkorra.util.TempBlock@1627e6c2, com.projectkorra.projectkorra.util.TempBlock@34312ad6, com.projectkorra.projectkorra.util.TempBlock@53a64d0, com.projectkorra.projectkorra.util.TempBlock@18523fbd, com.projectkorra.projectkorra.util.TempBlock@6019b8ea, com.projectkorra.projectkorra.util.TempBlock@da07c54, com.projectkorra.projectkorra.util.TempBlock@785e2aaa, com.projectkorra.projectkorra.util.TempBlock@75f01d04, com.projectkorra.projectkorra.util.TempBlock@6b4c58b9, com.projectkorra.projectkorra.util.TempBlock@23fc5d09, com.projectkorra.projectkorra.util.TempBlock@2288937d, com.projectkorra.projectkorra.util.TempBlock@312a84dd, com.projectkorra.projectkorra.util.TempBlock@32aebdd, com.projectkorra.projectkorra.util.TempBlock@ef01f07, com.projectkorra.projectkorra.util.TempBlock@3eebfb13, com.projectkorra.projectkorra.util.TempBlock@69c6093e, com.projectkorra.projectkorra.util.TempBlock@56bee844, com.projectkorra.projectkorra.util.TempBlock@73f84d03, com.projectkorra.projectkorra.util.TempBlock@7f5908a5, com.projectkorra.projectkorra.util.TempBlock@2e90c66f, com.projectkorra.projectkorra.util.TempBlock@1d0988f6, com.projectkorra.projectkorra.util.TempBlock@474d93b2]
  player=CraftPlayer{name=MrZero}
  bPlayer=com.projectkorra.projectkorra.BendingPlayer@348e0010[
  permaRemoved=false
  toggled=true
  tremorSense=true
  illumination=true
  chiBlocked=false
  slowTime=0
  player=CraftPlayer{name=MrZero}
  uuid=7c4e7172-0dcf-3596-9012-2d70a1102759
  name=MrZero
  stance=<null>
  cooldownManager=com.projectkorra.projectkorra.util.DBCooldownManager@3ee590a6
  elements=[Air, Water, Earth, Fire, Chi]
  subelements=[Metal, Lava, Sand, Combustion, Lightning, Spiritual, Flight, Ice, Healing, Blood, Plant]
  abilities={1=Pull, 2=Punch, 3=Grapple, 4=Grab, 5=Freeze, 6=Spear}
  cooldowns={}
  toggledElements={Air=true, Fire=true, Earth=true, Water=true, Chi=true}
]
  flightHandler=com.projectkorra.projectkorra.util.FlightHandler@6e3d1ea9
  attributeModifiers={}
  attributeValues={}
  started=true
  removed=false
  hidden=false
  id=-2147223674
  startTime=1563045066996
  startTick=24897256
  attributesModified=true
]
  player=CraftPlayer{name=MrZero}
  bPlayer=com.projectkorra.projectkorra.BendingPlayer@348e0010[
  permaRemoved=false
  toggled=true
  tremorSense=true
  illumination=true
  chiBlocked=false
  slowTime=0
  player=CraftPlayer{name=MrZero}
  uuid=7c4e7172-0dcf-3596-9012-2d70a1102759
  name=MrZero
  stance=<null>
  cooldownManager=com.projectkorra.projectkorra.util.DBCooldownManager@3ee590a6
  elements=[Air, Water, Earth, Fire, Chi]
  subelements=[Metal, Lava, Sand, Combustion, Lightning, Spiritual, Flight, Ice, Healing, Blood, Plant]
  abilities={1=Pull, 2=Punch, 3=Grapple, 4=Grab, 5=Freeze, 6=Spear}
  cooldowns={}
  toggledElements={Air=true, Fire=true, Earth=true, Water=true, Chi=true}
]
  flightHandler=com.projectkorra.projectkorra.util.FlightHandler@6e3d1ea9
  attributeModifiers={}
  attributeValues={}
  started=true
  removed=false
  hidden=false
  id=-2147221944
  startTime=1563045090865
  startTick=24897737
  attributesModified=true
]
```
Paper 1.13.2
ProjectKorra v1.8.8

**Comment by PhanaticD** [comment]
this was fixed already, you can compile the 1.13 branch to get latest changes
