### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world

### ISSUE THREAD

**Issue by andris155** [ProjectKorra/ProjectKorra#999]
```
[16:07:01] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
[16:07:01] [Server thread/WARN]: 	at org.bukkit.Location.distanceSquared(Location.java:483)
[16:07:01] [Server thread/WARN]: 	at org.bukkit.Location.distance(Location.java:466)
[16:07:01] [Server thread/WARN]: 	at com.projectkorra.projectkorra.waterbending.ice.PhaseChange.resetMeltLocation(PhaseChange.java:192)
[16:07:01] [Server thread/WARN]: 	at com.projectkorra.projectkorra.waterbending.ice.PhaseChange.progress(PhaseChange.java:117)
[16:07:01] [Server thread/WARN]: 	at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:251)
[16:07:01] [Server thread/WARN]: 	at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:105)
[16:07:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[16:07:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[16:07:01] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[16:07:01] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:07:01] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[16:07:01] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[16:07:01] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:07:01] [Server thread/ERROR]: com.projectkorra.projectkorra.waterbending.ice.PhaseChange@1f7b8a72[
  active_types=[Custom, Freeze, Melt]
  blocks=[com.projectkorra.projectkorra.util.TempBlock@41e91966, com.projectkorra.projectkorra.util.TempBlock@7d2b482f, com.projectkorra.projectkorra.util.TempBlock@6a4007ad, com.projectkorra.projectkorra.util.TempBlock@5fbe8cc1, com.projectkorra.projectkorra.util.TempBlock@efd8e1e, com.projectkorra.projectkorra.util.TempBlock@43d5aa89, com.projectkorra.projectkorra.util.TempBlock@11622fab, com.projectkorra.projectkorra.util.TempBlock@20aa0447, com.projectkorra.projectkorra.util.TempBlock@3d30f513, com.projectkorra.projectkorra.util.TempBlock@289f31e8, com.projectkorra.projectkorra.util.TempBlock@5300fa01, com.projectkorra.projectkorra.util.TempBlock@66b6f27f, com.projectkorra.projectkorra.util.TempBlock@4b7bb534, com.projectkorra.projectkorra.util.TempBlock@115b8176, com.projectkorra.projectkorra.util.TempBlock@6422d05c, com.projectkorra.projectkorra.util.TempBlock@149d3faf, com.projectkorra.projectkorra.util.TempBlock@24a219ae, com.projectkorra.projectkorra.util.TempBlock@2ca0e75, com.projectkorra.projectkorra.util.TempBlock@642b998a, com.projectkorra.projectkorra.util.TempBlock@70e264e4, com.projectkorra.projectkorra.util.TempBlock@1cb38778, com.projectkorra.projectkorra.util.TempBlock@160eb642, com.projectkorra.projectkorra.util.TempBlock@57c6edee, com.projectkorra.projectkorra.util.TempBlock@4f12d6, com.projectkorra.projectkorra.util.TempBlock@46afc5b0, com.projectkorra.projectkorra.util.TempBlock@5d5f146a, com.projectkorra.projectkorra.util.TempBlock@74ba1236, com.projectkorra.projectkorra.util.TempBlock@7967094, com.projectkorra.projectkorra.util.TempBlock@69b1d652, com.projectkorra.projectkorra.util.TempBlock@163633f, com.projectkorra.projectkorra.util.TempBlock@5935e272, com.projectkorra.projectkorra.util.TempBlock@5b3644b6, com.projectkorra.projectkorra.util.TempBlock@1e019226, com.projectkorra.projectkorra.util.TempBlock@3b0b938, com.projectkorra.projectkorra.util.TempBlock@775cb4f6, com.projectkorra.projectkorra.util.TempBlock@49482b42, com.projectkorra.projectkorra.util.TempBlock@4a388c18, com.projectkorra.projectkorra.util.TempBlock@34f491d4, com.projectkorra.projectkorra.util.TempBlock@69e771f0, com.projectkorra.projectkorra.util.TempBlock@30d39ba1, com.projectkorra.projectkorra.util.TempBlock@e7e9d19, com.projectkorra.projectkorra.util.TempBlock@4ca9ca7a, com.projectkorra.projectkorra.util.TempBlock@4a81b1a1, com.projectkorra.projectkorra.util.TempBlock@721294c6, com.projectkorra.projectkorra.util.TempBlock@6e4814a8, com.projectkorra.projectkorra.util.TempBlock@2b069d30, com.projectkorra.projectkorra.util.TempBlock@31d621fa]
  r=java.util.Random@1a2fc9db
  sourceRange=14
  freezeCooldown=500
  freezeRadius=6
  depth=2
  controlRadius=50.0
  meltLoc=Location{world=CraftWorld{name=world_nether},x=-993.2616853245249,y=46.20114722325367,z=-609.4474748979605,pitch=51.799946,yaw=-310.6637}
  meltCooldown=2000
  meltRadius=1
  meltMaxRadius=14
  meltSpeed=16.0
  meltTicks=0.0
  allowMeltFlow=true
  melted_blocks=[]
  player=CraftPlayer{name=DreaKii}
  bPlayer=com.projectkorra.projectkorra.BendingPlayer@51d1bebc[
  permaRemoved=false
  toggled=true
  tremorSense=true
  illumination=true
  chiBlocked=false
  slowTime=0
  player=CraftPlayer{name=DreaKii}
  uuid=5af7a12c-0177-3b4d-b0ee-a115086bc5a9
  name=DreaKii
  stance=<null>
  cooldownManager=com.projectkorra.projectkorra.util.DBCooldownManager@2664fcf1
  elements=[Water]
  subelements=[Ice]
  abilities={1=Torrent, 2=OctopusForm, 3=PhaseChange, 4=IceBlast}
  cooldowns={}
  toggledElements={Fire=true, Earth=true, Air=true, Chi=true, Water=true}
]
  flightHandler=com.projectkorra.projectkorra.util.FlightHandler@426188f7
  attributeModifiers={}
  attributeValues={}
  started=true
  removed=false
  hidden=false
  id=-2147467628
  startTime=1562939836085
  startTick=365652638
  attributesModified=true
]
```
Paper 1.13.2
ProjectKorra v1.8.8

**Comment by PhanaticD** [comment]
fixed and it is in my latest PR

**Comment by andris155** [comment]
Thanks!
